export { default as CollectionPage } from "./Collection"
export { default as CallbackLoginPage } from "./Callback"
export { default as SearchPage } from "./Search"
export { default as SettingsHomePage } from "./Settings/Home"
export { default as SettingsStatsPage } from "./Settings/Stats"
