name: 🚀 Deploy!

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"
    release:
        types:
            - published
    workflow_dispatch:

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        permissions:
            contents: read
            deployments: write

        steps:
            - uses: actions/checkout@v4

            - name: 🏗 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - name: Set Version
              run: |
                VERSION=$(jq -r '.version' frontend/package.json)
                GIT_COMMIT=$(git rev-parse --short HEAD)
                echo "VITE_VER=${VERSION}-${GIT_COMMIT}" >> frontend/.env.production

            - name: 📦 Build Site
              run: cd frontend && npm ci && npm run build:ion

            - name: 🚛 Publish Site
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: discog
                  directory: ./frontend/dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.event_name == 'release' && 'main' || 'not-hotdog' }}
