name: 🚀 Deploy!

on:
    push:
        branches:
            - main
        paths:
            - "frontend/**"
    release:
        types:
            - published
    workflow_dispatch:

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        runs-on: ubuntu-latest

        permissions:
            contents: read
            deployments: write

        steps:
            - uses: actions/checkout@v4

            - name: 🏗 Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x


            - name: 🔎 Identify Commit Hash
              id: commit
              uses: prompt/actions-commit-hash@v3
        
            - name: 🔎 Identify version
              id: get_version
              uses: battila7/get-version-action@v2
        
            - name: 🦸 change version in NPM
              uses: reedyuk/npm-version@1.2.2
              with:
                version: ${{ steps.get_version.outputs.version-without-v  }}-${{ steps.commit.outputs.short }}
                package: "frontend/"
                git-tag-version: "false"

            - name: 📦 Build Site
              run: cd frontend && npm ci && npm run build:ion

            - name: 🚛 Publish Site
              uses: cloudflare/pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  projectName: discog
                  directory: ./frontend/dist
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  branch: ${{ github.event_name == 'release' && 'main' || 'not-hotdog' }}
